services:
  newsmix:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Docker
      - GITCOMMITURL=${GITCOMMITURL}
    volumes:
      - newsmix:/mount_dir
    restart: unless-stopped

volumes:
  newsmix:
    external: true